version: '3'
services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    environment:
      - POSTGRES_DB=llmops
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: